@LLMTranslateService.Api_HostAddress = http://localhost:5073

### es-MX
GET {{LLMTranslateService.Api_HostAddress}}/weatherforecast/
Accept: application/json
Accept-Language: es-MX

### en-US
GET {{LLMTranslateService.Api_HostAddress}}/weatherforecast/
Accept: application/json
Accept-Language: en-US

### fr-FR
GET {{LLMTranslateService.Api_HostAddress}}/weatherforecast/
Accept: application/json
Accept-Language: fr-FR
